language: python
python:
  - "3.6"
install:
  - pip install pipenv && pipenv install --dev --system --deploy
stages:
- commit
- package
jobs:
  include:
    - stage: commit
      script: python3 restaurant_service/manage.py test
      script: flake8
    - stage: package
      script:
        - docker build -t restaurant_service .
        - docker images
