version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/restaurant_service
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0:8000"
