version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "pipenv run python restaurant_service/manage.py migrate && pipenv run python restaurant_service/manage.py runserver 0:8000"
