# Generated by Django 2.0.5 on 2018-05-15 21:42
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
        ),
    ]
